Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,6 +38,13 @@ jobs:
           cd LibraryManagementSystem
           mvn clean test jacoco:report
 
+      - name: Debug Jacoco Path
+        run: |
+          cd LibraryManagementSystem
+          echo "----- Checking Jacoco Report Folder -----"
+          ls -R target/site/jacoco || echo "Jacoco folder NOT found!"
+          echo "-----------------------------------------"
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarqube-scan-action@v5.0.0
         with:
@@ -45,10 +52,11 @@ jobs:
             -Dsonar.projectKey=sadeelandbana_Library-Management-System
             -Dsonar.organization=sadeelandbana0405121
             -Dsonar.projectBaseDir=LibraryManagementSystem
-            -Dsonar.java.binaries=target/classes
-            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
-            -Dsonar.coverage.exclusions=**/com/library/app/**,**/*Screen.java,**/*Frame.java,**/*Main*.java,**/EmailNotifier.java,**/Observer.java
-            -Dsonar.exclusions=**/com/library/app/**,**/*Screen.java,**/*Frame.java,**/*Main*.java,**/EmailNotifier.java,**/Observer.java
+            -Dsonar.java.binaries=LibraryManagementSystem/target/classes
+            -Dsonar.java.coveragePlugin=jacoco
+            -Dsonar.coverage.jacoco.xmlReportPaths=LibraryManagementSystem/target/site/jacoco/jacoco.xml
+            -Dsonar.coverage.exclusions=**/com/library/app/**,**/com/library/app/**/*,**/*Screen*.java,**/*Frame*.java,**/*RoundedBorder*.java,**/*GUI*.java,**/*Main*.java,**/EmailNotifier.java,**/Observer.java
+            -Dsonar.exclusions=**/com/library/app/**,**/com/library/app/**/*,**/*Screen*.java,**/*Frame*.java,**/*RoundedBorder*.java,**/*GUI*.java,**/*Main*.java,**/EmailNotifier.java,**/Observer.java
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
